### ISSUE TITLE
No option for Linkedin and google +

### ISSUE THREAD

**Issue by Harrrrry** [Oefenweb/cakephp-social-media#11]
Please advice me if there is any way to share something on Linkedin and google +

**Comment by tersmitten** [comment]
Sure, but not in this plugin at the moment. We're open for pull request, but you might want to have a look [at](https://github.com/FriendsOfCake/awesome-cakephp/tree/cake2#social).

**Comment by Harrrrry** [comment]
hi the given reference for cakephp-social-share:3.0.*, i am using 2.*.*

**Comment by tersmitten** [comment]
There's also 2.* branch

**Comment by Harrrrry** [comment]
can u specify the name please

**Comment by tersmitten** [comment]
https://github.com/drmonkeyninja/cakephp-social-share/tree/2.x
